Category.create!([
  {name: "Romantic", picture: "category_romantic.jpg", coins: 200},
  {name: "Adventure", picture: "category_adventure.jpg", coins: 100},
  {name: "Romantic", picture: "category_romantic.jpg", coins: 200},
  {name: "Adventure", picture: "category_adventure.jpg", coins: 100}
])
Challenge.create!([
  {title: "Romantic challenge 1", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 2", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 3", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 4", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 5", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 6", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 7", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 8", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 9", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 10", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 11", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 12", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 13", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 14", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 15", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 1", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 2", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 3", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 4", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 5", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 6", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 7", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 8", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 9", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 10", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 11", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 12", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 13", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 14", description: "This is what you have to do", deadline: 20, category_id: 1},
  {title: "Romantic challenge 15", description: "This is what you have to do", deadline: 20, category_id: 1}
])
