# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.second)


Category.create(name: "Romantic", kisses: 200)
Category.create(name: "Adventure", kisses: 100)
Category.create(name: "Spicy", kisses: 500)

Challenge.create(title: " Back massage  ", description: " Have all ready for when your love arrives at home: nice relaxing music, a candle lit and have him /her... ", gender: "male", deadline:  5, category_id:  Category.first.id)
Challenge.create(title: " Full body massage ", description: " Have all ready for when your love arrives at home: nice relaxing music, a candle lit and have him /her... ", gender: "male", deadline:  5, category_id:  Category.first.id)
Challenge.create(title: " Play date ", description: " Break away from the dinner-and-movie pattern by opting instead for a play date. Try one of your favorite old-school activities, like hitting a roller rink, laser tag center or arcade. Cap it all off with an indulgent meal from one of your fave childhood eateries, like Medieval Times or McDonald's.  ", gender: "female", deadline:  5, category_id:  Category.first.id)
Challenge.create(title: " Practical jokes ", description: " Tease your guy with little practical jokes. Have an object, like a ridiculous fake plant, that he's given you a hard time about? Hide it around his place. Whether it's waiting for him in the fridge, the washer, or his computer's desktop wallpaper, it's destined to deliver a genuine laugh. ", gender: "male", deadline:  5, category_id:  Category.first.id)
Challenge.create(title: " Around the world food trip  ", description: " Orchestrate an around the world food tour in place of the usual restaurant night. Kick off the night with Spanish tapas, then continue your Euro trip with a French main course before wrapping up with dessert at a cute gelateria.  ", gender: "male", deadline:  5, category_id:  Category.first.id)
Challenge.create(title: " Shooting 'em all  ", description: " Experience a joint adrenaline rush by unloading on perps at a paintball or shooting rangethen head home to use that energy on each other. ", gender: "female", deadline:  5, category_id:  Category.first.id)
Challenge.create(title: " Back to high-school ", description: " Enjoy a little high school-style PDA (public display of affection) and relive those can't-keep-your-hands-off-each-other days during a night out. While in the middle of the packed dance floor (and preferably a safe distance from eye-rolling friends), pull him in closer to you for a seductive kiss. The music and environment can lend an extra rush to the experience that'll make him it hard for him to wait for the trip home to have you. ", gender: "female", deadline:  5, category_id:  Category.first.id)
Challenge.create(title: " Getting out of your element ", description: " Try a cool activity together that gets you out of your element. Flash sale sites like LivingSocial tend to offer deals on awesome excursions like zip-lining, extreme driving, and more, so you can get your kicks while scoring sweet, sweet discounts to boot.  ", gender: "female", deadline:  5, category_id:  Category.second.id)
Challenge.create(title: " Dance party ", description: " While you're cooking or going about other daily rituals, turn up one of your shared favorite artists and start grooving. Even if he tries to rein in your silly side, the moment he comes over to curb your running man can lead to a sweet, intimate hug and kiss. ", gender: "male", deadline:  5, category_id:  Category.second.id)
Challenge.create(title: " TIckets for a special event ", description: " Surprise him with a pair of tickets to an event you know he's psyched about. You'll gain major points and it'll give him the chance to introduce you to something new (making him feel extra manly) as you two spend an awesome evening together. ", gender: "male", deadline:  5, category_id:  Category.second.id)
Challenge.create(title: " Post-it note  ", description: " Write him a short, sexy message on a sticky note and stick it in an unexpected place for him to find. When he opens his glasses case or starts his car, he'll have an unprompted reminder that you care.  ", gender: "female", deadline:  5, category_id:  Category.second.id)
Challenge.create(title: " Coocking class for two  ", description: " Team up and take a cooking class at your favorite restaurant. (Check out its calendar online; plenty offer various cooking events.) You can tease each other's horrific chopping skills while picking up some helpful new tips. Later that week, try to recreate the meal together at home. ", gender: "female", deadline:  5, category_id:  Category.second.id)
Challenge.create(title: " Video Game duel ", description: " Challenge him to a duel at his new video game (before he's had a chance to scope out the cheat sheets online) and engage in some flirtatious smack-talking. Up the ante by placing a bet; for example, loser owes the winner a sexy favor of their choosing. Careful though: With all that heat, you might not make it through the first round… ", gender: "male", deadline:  5, category_id:  Category.second.id)
Challenge.create(title: " Spicy shopping  ", description: " Though you'll be hard-pressed to find a guy that can't get enough of accompanying his lady while shopping, you might notice a change in attitude if you invite him to stop into a lingerie shopespecially if he's given free rein to pick out some of his favorite underthings for you to model at home.  ", gender: "female", deadline:  5, category_id:  Category.last.id)
Challenge.create(title: " Shades of grey  ", description: " Take a cue from 50 Shades of Grey and dog-ear a few of your favorite smokin' scenes to try out with your guy (er, sans the cheesy dialogue).  ", gender: "female", deadline:  5, category_id:  Category.last.id)
Challenge.create(title: " Dual purposes ", description: " Make a game out of picking out random items around the house and determining ways to incorporate them into bedroom play. Okay, maybe those porcelain frog figurines won't do, but those cashmere scarves might serve, shall we say, dual purposes? Whatever doesn't work can totally make for a good laugh. ", gender: "male", deadline:  5, category_id:  Category.last.id)
Challenge.create(title: " Toy store spree ", description: " Venture out on a shopping spreeat an adult toy store. In addition to cracking up at some of the over-the-top selections, you'll find that a trip can deliver steamy new surges of inspiration. Let him pick out pleasure props he's into while you load up on your own, then come to a sexy consensus.  ", gender: "female", deadline:  5, category_id:  Category.last.id)
Challenge.create(title: " Role play roulette  ", description: " Mix things up by trying your hand at role-play. Don't limit yourself to the same old stuff. Be creative and come up with cool scenarios, like rock star and groupieyour groupie.  ", gender: "male", deadline:  5, category_id:  Category.last.id)
Challenge.create(title: " Spicy vacation  ", description: " Even studies have proven that vacation sex is one of the hottest varieties. Too broke to jet off to the Caribbean? Experience the same fresh change of scene by indulging in a staycation. Check into a hotel of your picking and kick back with a killer bottle of wine and some room service. Don't forget to score a few dirty looks from stodgy older guests by playing some of your favorite throwback games in the indoor pool. ", gender: "female", deadline:  5, category_id:  Category.last.id)
Challenge.create(title: " Clothes trail ", description: " Before your guy gets home, leave a trail of your clothes from the front door to the bedroom. When he finally appears, expecting an explanation for the mess, he'll be too dumbfounded by the sight of a stripped-down you to do anything other than pounce. ", gender: "male", deadline:  5, category_id:  Category.last.id)


# Category.create(name: "Romantic", kisses: 200)
# Category.create(name: "Adventure", kisses: 100)
# Category.create(name: "Spicy", kisses: 300)

# Challenge.create(title: "Challenge 1",description: "This is what you have to do",gender: "male", deadline: 10, category_id: Category.first.id)
# Challenge.create(title: "Challenge 2", description: "This is what you have to do",gender: "male", deadline: 10, category_id: Category.first.id)
# Challenge.create(title: "Challenge 3", description: "This is what you have to do",gender: "male", deadline: 10, category_id: Category.first.id)
# Challenge.create(title: "Challenge 4", description: "This is what you have to do",gender: "male", deadline: 10, category_id: Category.first.id)
# Challenge.create(title: "Callenge 16", description: "This is what you have to do",gender: "male", deadline: 10,  category_id: Category.first.id)
# Challenge.create(title: "Challenge 17", description: "This is what you have to do",gender: "both", deadline: 10, category_id: Category.first.id)
# Challenge.create(title: " challenge 5", description: "This is what you have to do",gender: "male", deadline: 10, category_id: Category.first.id)
# Challenge.create(title: " challenge 6", description: "This is what you have to do",gender: "male", deadline: 10,category_id: Category.first.id)
# Challenge.create(title: " challenge 7", description: "This is what you have to do",gender: "male", deadline: 10,category_id: Category.first.id)
# Challenge.create(title: " challenge 8", description: "This is what you have to do",gender: "male", deadline: 10, category_id: Category.first.id)
# Challenge.create(title: " challenge 9", description: "This is what you have to do",gender: "female", deadline: 10, category_id: Category.first.id)
# Challenge.create(title: " challenge 10", description: "This is what you have to do",gender: "both", deadline: 10, category_id: Category.first.id)
# Challenge.create(title: " challenge 11", description: "This is what you have to do",gender: "female", deadline: 10,category_id: Category.first.id)
# Challenge.create(title: " challenge 12", description: "This is what you have to do",gender: "female", deadline: 10,category_id: Category.first.id)
# Challenge.create(title: " challenge 13", description: "This is what you have to do",gender: "female", deadline: 10, category_id: Category.first.id)
# Challenge.create(title: " challenge 14", description: "This is what you have to do",gender: "female", deadline: 10,  category_id: Category.first.id)
# Challenge.create(title: " challenge 15", description: "This is what you have to do",gender: "female", deadline: 10, category_id: Category.first.id)


# Challenge.create(title: "Challenge 1", description: "This is what you have to do",gender: "male", deadline: 10, category_id: Category.second.id)
# Challenge.create(title: "Challenge 2", description: "This is what you have to do",gender: "male", deadline: 10, category_id: Category.second.id)
# Challenge.create(title: "Challenge 3", description: "This is what you have to do",gender: "male", deadline: 10, category_id: Category.second.id)
# Challenge.create(title: "Challenge 4", description: "This is what you have to do",gender: "male", deadline: 10, category_id: Category.second.id)
# Challenge.create(title: "Callenge 16", description: "This is what you have to do",gender: "male", deadline: 10,  category_id: Category.second.id)
# Challenge.create(title: "Challenge 17", description: "This is what you have to do",gender: "both", deadline: 10, category_id: Category.second.id)
# Challenge.create(title: " challenge 5", description: "This is what you have to do",gender: "male", deadline: 10, category_id: Category.second.id)
# Challenge.create(title: " challenge 6", description: "This is what you have to do",gender: "male", deadline: 10,category_id: Category.second.id)
# Challenge.create(title: " challenge 7", description: "This is what you have to do",gender: "male", deadline: 10,category_id: Category.second.id)
# Challenge.create(title: " challenge 8", description: "This is what you have to do",gender: "male", deadline: 10, category_id: Category.second.id)
# Challenge.create(title: " challenge 9", description: "This is what you have to do",gender: "female", deadline: 10, category_id: Category.second.id)
# Challenge.create(title: " challenge 10", description: "This is what you have to do",gender: "both", deadline: 10, category_id: Category.second.id)
# Challenge.create(title: " challenge 11", description: "This is what you have to do",gender: "female", deadline: 10,category_id: Category.second.id)
# Challenge.create(title: " challenge 12", description: "This is what you have to do",gender: "female", deadline: 10,category_id: Category.second.id)
# Challenge.create(title: " challenge 13", description: "This is what you have to do",gender: "female", deadline: 10, category_id: Category.second.id)
# Challenge.create(title: " challenge 14", description: "This is what you have to do",gender: "female", deadline: 10,  category_id: Category.second.id)
# Challenge.create(title: " challenge 15", description: "This is what you have to do",gender: "female", deadline: 10, category_id: Category.second.id)


# Challenge.create(title: "Challenge 1", description: "This is what you have to do",gender: "male", deadline: 10, category_id: Category.last.id)
# Challenge.create(title: "Challenge 2", description: "This is what you have to do",gender: "male", deadline: 10, category_id: Category.last.id)
# Challenge.create(title: "Challenge 3", description: "This is what you have to do",gender: "male", deadline: 10, category_id: Category.last.id)
# Challenge.create(title: "Challenge 4", description: "This is what you have to do",gender: "male", deadline: 10, category_id: Category.last.id)
# Challenge.create(title: "Callenge 16", description: "This is what you have to do",gender: "male", deadline: 10,  category_id: Category.last.id)
# Challenge.create(title: "Challenge 17", description: "This is what you have to do",gender: "both", deadline: 10, category_id: Category.last.id)
# Challenge.create(title: " challenge 5", description: "This is what you have to do",gender: "male", deadline: 10, category_id: Category.last.id)
# Challenge.create(title: " challenge 6", description: "This is what you have to do",gender: "male", deadline: 10,category_id: Category.last.id)
# Challenge.create(title: " challenge 7", description: "This is what you have to do",gender: "male", deadline: 10,category_id: Category.last.id)
# Challenge.create(title: " challenge 8", description: "This is what you have to do",gender: "male", deadline: 10, category_id: Category.last.id)
# Challenge.create(title: " challenge 9", description: "This is what you have to do",gender: "female", deadline: 10, category_id: Category.last.id)
# Challenge.create(title: " challenge 10", description: "This is what you have to do",gender: "both", deadline: 10, category_id: Category.last.id)
# Challenge.create(title: " challenge 11", description: "This is what you have to do",gender: "female", deadline: 10,category_id: Category.last.id)
# Challenge.create(title: " challenge 12", description: "This is what you have to do",gender: "female", deadline: 10,category_id: Category.last.id)
# Challenge.create(title: " challenge 13", description: "This is what you have to do",gender: "female", deadline: 10, category_id: Category.last.id)
# Challenge.create(title: " challenge 14", description: "This is what you have to do",gender: "female", deadline: 10,  category_id: Category.last.id)
# Challenge.create(title: " challenge 15", description: "This is what you have to do",gender: "female", deadline: 10, category_id: Category.last.id)
